"""fix type in status

Revision ID: 21ca6507b862
Revises: ecac1135941a
Create Date: 2025-05-20 14:31:45.535232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ca6507b862'
down_revision = 'ecac1135941a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.drop_column('Status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
