"""Updates rental model

Revision ID: 3b9a3fcdd01d
Revises: 20c317256407
Create Date: 2025-05-20 13:59:58.071224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9a3fcdd01d'
down_revision = '20c317256407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('checked_in', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_column('checked_in')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
