"""adds columns for video model

Revision ID: b8cd731f5650
Revises: 4b75dd291e74
Create Date: 2025-05-07 08:44:38.617054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8cd731f5650'
down_revision = '4b75dd291e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('total_inventory', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('total_inventory')
        batch_op.drop_column('release_date')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
