"""Change 'checked_in' to 'status' in rental model

Revision ID: ecac1135941a
Revises: 3b9a3fcdd01d
Create Date: 2025-05-20 14:28:58.767705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecac1135941a'
down_revision = '3b9a3fcdd01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.String(), nullable=False))
        batch_op.drop_column('checked_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('Status')

    # ### end Alembic commands ###
